

    
-- Question 1: Which cities and countries have the highest level of transaction revenues on the site?**


SQL Queries:

SELECT
    country,
    city,
    SUM(totaltransactionrevenue) AS total_revenue
FROM
    all_sessions
   WHERE totaltransactionrevenue IS NOT NULL
GROUP BY
    country, city
ORDER BY
    total_revenue DESC
LIMIT 10; 


Answer:"country","city","total_revenue"
"United States","not available in demo dataset","4953080000"
"United States","San Francisco","1263320000"
"United States","Sunnyvale","992230000"
"United States","Atlanta","854440000"
"United States","Palo Alto","608000000"
"Israel","Tel Aviv-Yafo","602000000"
"United States","New York","530360000"
"United States","Mountain View","483360000"
"United States","Los Angeles","479480000"
"United States","Chicago","449520000"



**Question 2: What is the average number of products ordered from visitors in each city and country?**


SQL Queries:

SELECT AVG (totalordered) AS avg_products_ordered	
FROM sales_report s
JOIN all_sessions a
ON s.productsku= a.productsku
WHERE totalordered IS NOT NULL  
GROUP BY country, city
ORDER BY avg_products_ordered DESC;


Answer:

country","avg_products_ordered"
"Kuwait","169.5"
"Saudi Arabia","96.3"
"Oman","85.0"
"Ethiopia","85.0"
"Laos","85.0"
"Papua New Guinea","57.5"
"Honduras","56.0"
"Trinidad & Tobago","47.0"
"Kazakhstan","43.0"
"South Korea","36.4"
"Hong Kong","35.5"
"Guatemala","33.1"
"Réunion","32.0"
"Mauritius","31.0"
"Nepal","30.5"
"Morocco","30.3"
"Ukraine","30.1"
"Montenegro","30.0"
"Moldova","30.0"
"Mali","30.0"
"Spain","29.2"
"Malaysia","29.1"
"Greece","29.0"
"Mexico","28.9"
"Romania","28.5"
"Italy","28.1"
"Japan","28.0"
"Denmark","27.9"
"Czechia","26.4"
"Ireland","26.2"
"Germany","25.7"
"Israel","25.7"
"Brazil","25.3"
"Taiwan","24.6"
"Russia","24.3"
"Singapore","23.8"
"Myanmar (Burma)","23.7"
"Pakistan","23.1"
"Portugal","23.0"
"Slovenia","23.0"
"Georgia","22.8"
"United Arab Emirates","22.4"
"Venezuela","22.1"
"(not set)","21.9"
"Thailand","21.8"
"United Kingdom","20.9"
"Colombia","20.7"
"United States","20.4"
"Canada","20.3"
"Netherlands","19.6"
"Australia","19.0"
"Vietnam","18.1"
"India","17.8"
"Argentina","17.8"
"Macedonia (FYROM)","17.7"
"Albania","16.7"
"Belgium","16.3"
"Kyrgyzstan","16.0"
"Armenia","16.0"
"Peru","15.9"
"Costa Rica","15.8"
"Switzerland","15.7"
"Indonesia","15.5"
"Côte d’Ivoire","15.5"
"Panama","15.0"
"Tunisia","14.8"
"Nigeria","14.8"
"France","14.7"
"Bulgaria","14.0"
"Turkey","13.7"
"Sweden","13.5"
"Finland","13.5"
"Poland","13.1"
"Uganda","13.0"
"Paraguay","13.0"
"Philippines","12.9"
"Slovakia","12.6"
"Puerto Rico","12.3"
"Dominican Republic","12.1"
"Zimbabwe","12.0"
"Lithuania","11.9"
"Hungary","11.7"
"New Zealand","11.7"
"Chile","11.6"
"Bahrain","11.5"
"Jersey","11.0"
"South Africa","10.2"
"Serbia","9.5"
"Algeria","9.0"
"Tanzania","9.0"
"Uruguay","8.6"
"Egypt","8.6"
"Croatia","7.6"
"Ghana","7.5"
"Norway","7.3"
"Bangladesh","6.7"
"El Salvador","6.5"
"Austria","5.1"
"Sri Lanka","5.0"
"Jordan","5.0"
"Botswana","5.0"
"China","4.6"
"Cambodia","4.3"
"Bolivia","4.0"
"Latvia","3.2"
"Palestine","3.0"
"Jamaica","3.0"
"Estonia","2.6"
"Bahamas","2.5"
"Cyprus","2.5"
"Belarus","2.0"
"Macau","2.0"
"Ecuador","2.0"
"Brunei","2.0"
"Martinique","2.0"
"Bosnia & Herzegovina","2.0"
"Gibraltar","2.0"
"Sint Maarten","2.0"
"Qatar","1.3"
"Maldives","1.0"
"Kosovo","1.0"
"Kenya","0.7"
"Iraq","0.5"
"Iceland","0.0"
"Malta","0.0"

By city

city","avg_products_ordered"
"Riyadh","319.0"
"Brno","319.0"
"Rexburg","250.5"
"Sacramento","189.0"
"Lisbon","189.0"
"Kalamazoo","105.0"
"Saint Petersburg","101.3"
"Longtan District","97.0"
"Sherbrooke","97.0"
"Nashville","94.0"
"Pune","77.5"
"Shinjuku","73.0"
"Westville","70.0"
"Rio de Janeiro","65.3"
"Vladivostok","62.0"
"Bellingham","62.0"
"Santa Fe","60.0"
"San Antonio","58.2"
"Seoul","57.6"
"Menlo Park","51.5"
"Athens","51.3"
"Boston","50.5"
"Palo Alto","48.2"
"Zhongli District","46.0"
"Indore","44.0"
"Belo Horizonte","43.0"
"Dubai","42.3"
"Salem","40.6"
"Munich","39.8"
"Hanoi","37.7"
"Santa Clara","35.9"
"Hamburg","34.3"
"Pozuelo de Alarcon","34.3"
"Dublin","33.9"
"Bangkok","32.9"
"Hong Kong","32.8"
"Phoenix","32.2"
"San Bruno","31.6"
"Bellflower","30.0"
"Cork","30.0"
"Toronto","27.9"
"Mumbai","27.7"
"Tel Aviv-Yafo","27.5"
"Milan","27.2"
"Seattle","26.7"
"Madrid","26.5"
"Rome","26.5"
"Mississauga","24.7"
"Philadelphia","24.3"
"Charlotte","24.2"
"Irvine","23.6"
"Pittsburgh","23.5"
"Melbourne","23.0"
"Ann Arbor","22.7"
"Mountain View","22.7"
"Los Angeles","22.6"
"(not set)","22.4"
"Amsterdam","22.1"
"San Francisco","21.2"
"Sao Paulo","21.0"
"Vancouver","21.0"
"Santiago","20.8"
"Sydney","20.5"
"Austin","20.4"
"Bogota","20.4"
"not available in demo dataset","19.9"
"Redmond","19.7"
"Calgary","19.5"
"Chicago","19.4"
"Sunnyvale","19.4"
"London","18.9"
"Kitchener","18.8"
"Kolkata","18.6"
"Oakland","18.5"
"Berlin","18.4"
"New York","18.2"
"Cupertino","18.0"
"Ahmedabad","18.0"
"Chennai","17.9"
"Ho Chi Minh City","17.9"
"Redwood City","17.8"
"Hyderabad","17.6"
"Kuala Lumpur","17.3"
"Barcelona","17.2"
"Houston","16.7"
"Warsaw","16.0"
"Ghent","16.0"
"Dallas","16.0"
"Copenhagen","16.0"
"Singapore","15.9"
"San Jose","15.8"
"Bucharest","15.3"
"Prague","15.0"
"La Victoria","14.8"
"Quebec City","14.0"
"Budapest","14.0"
"Perth","14.0"
"Paris","13.7"
"Lake Oswego","13.3"
"Montreal","13.3"
"Asuncion","13.0"
"Wrexham","13.0"
"Chandigarh","13.0"
"Akron","13.0"
"The Dalles","13.0"
"LaFayette","13.0"
"New Delhi","12.8"
"Mexico City","12.5"
"Detroit","12.3"
"Washington","12.2"
"Kiev","12.1"
"Zurich","11.9"
"Cambridge","11.8"
"Gurgaon","11.8"
"Osaka","11.6"
"Minato","11.5"
"Bengaluru","11.2"
"Jaipur","11.0"
"Ipoh","11.0"
"Stockholm","10.6"
"Istanbul","10.5"
"Manila","10.5"
"San Diego","9.9"
"Jakarta","9.8"
"Atlanta","9.8"
"Taguig","9.7"
"Burnaby","9.5"
"South San Francisco","8.7"
"Kirkland","8.1"
"Moscow","8.1"
"Buenos Aires","8.0"
"Courbevoie","7.5"
"Montevideo","7.5"
"Yokohama","7.3"
"Medellin","7.0"
"Thessaloniki","7.0"
"Frankfurt","7.0"
"St. Louis","7.0"
"East Lansing","7.0"
"Oviedo","6.5"
"Bandung","6.0"
"Nanded","6.0"
"Tempe","6.0"
"Helsinki","6.0"
"Kharagpur","6.0"
"Fremont","5.8"
"San Mateo","5.5"
"Boulder","5.3"
"Denver","5.3"
"Timisoara","5.3"
"Quezon City","5.2"
"University Park","5.0"
"Jacksonville","5.0"
"Columbia","5.0"
"Ashburn","4.0"
"Marseille","4.0"
"Doha","4.0"
"Poznan","4.0"
"Cluj-Napoca","4.0"
"Richardson","4.0"
"Brussels","4.0"
"Eau Claire","3.9"
"Portland","3.8"
"Izmir","3.5"
"Colombo","3.5"
"Petaling Jaya","3.0"
"Madison","3.0"
"Adelaide","3.0"
"Wellesley","3.0"
"Stanford","3.0"
"Zagreb","3.0"
"Druid Hills","3.0"
"Jersey City","2.7"
"Milpitas","2.6"
"Orlando","2.5"
"Brisbane","2.3"
"Las Vegas","2.0"
"Iasi","2.0"
"Salford","2.0"
"Chico","2.0"
"Antwerp","1.5"
"Council Bluffs","1.5"
"Maracaibo","1.5"
"Norfolk","1.0"
"Greer","1.0"
"Piscataway Township","1.0"
"Oslo","1.0"
"Villeneuve-d'Ascq","1.0"
"Rosario","1.0"
"Edmonton","1.0"
"Lahore","1.0"
"Patna","1.0"
"Vilnius","1.0"
"Kansas City","0.7"
"Vienna","0.5"
"Pleasanton","0.0"
"Karachi","0.0"
"Lucknow","0.0"
"Shibuya","0.0"
"Nagoya","0.0"
"Chuo","0.0"
"Makati","0.0"
"Forest Park","0.0"
"Hayward","0.0"
"Coventry","0.0"
"Panama City","0.0"
"San Salvador","0.0"
"Auckland","0.0"
"Bratislava","0.0"
"Manchester","0.0"
"Westlake Village","0.0"
"Minneapolis","0.0"
"Tampa","0.0"
"Nairobi","0.0"
"Fortaleza","0.0"
"South El Monte","0.0"
"Indianapolis","0.0"
"Goose Creek","0.0"
"Waterloo","0.0"
"St. John's","0.0"
"Marlboro","0.0"
"Beijing","0.0"





**Question 3: Is there any pattern in the types (product categories) of products ordered from visitors in each city and country?**


SQL Queries:

SELECT a.country, a.city, a.v2productcategory,
    COUNT(a.productsku) AS product_count
FROM
    all_sessions a
JOIN
    sales_report s ON a.productsku = s.productsku
GROUP BY
    a.country, a.city, a.v2productcategory
ORDER BY
    a.country, a.city, product_count DESC;

Answer:
"country","city","v2productcategory","total_products_ordered","total_revenue"
"United States","not available in demo dataset","Home/Nest/Nest-USA/","17","130182"
"United States","Mountain View","Home/Nest/Nest-USA/","17","129751"
"United States","Mountain View","Home/Office/Notebooks & Journals/","1","37961"
"United States","Los Angeles","Home/Drinkware/Water Bottles and Tumblers/","1","36406"
"United States","Palo Alto","Home/Nest/Nest-USA/","3","36064"
"United States","San Francisco","Home/Nest/Nest-USA/","4","33114"
"United States","Sunnyvale","Home/Drinkware/Water Bottles and Tumblers/","1","33066"
"United States","Los Angeles","Home/Nest/Nest-USA/","2","30844"
"United States","Sunnyvale","Home/Nest/Nest-USA/","4","30498"
"United States","New York","Home/Nest/Nest-USA/","3","26560"
"United States","Seattle","Home/Nest/Nest-USA/","2","23154"
"United States","Pittsburgh","Home/Nest/Nest-USA/","1","22288"
"Mexico","not available in demo dataset","Home/Nest/Nest-USA/","1","20298"
"Mexico","Mexico City","Home/Nest/Nest-USA/","1","18706"
"Morocco","not available in demo dataset","Home/Nest/Nest-USA/","1","18706"
"United States","not available in demo dataset","Home/Bags/","26","15621"
"United States","Chicago","Nest-USA","1","14006"
"United States","not available in demo dataset","${escCatTitle}","1","13944"
"United States","not available in demo dataset","Home/Drinkware/Water Bottles and Tumblers/","3","13360"
"United States","San Francisco","Nest-USA","1","13328"
"United States","not available in demo dataset","Home/Drinkware/","9","13163"
"United States","Chicago","Home/Nest/Nest-USA/","2","12448"
"United States","Nashville","Nest-USA","1","11186"
"United States","not available in demo dataset","(not set)","19","10609"
"United Kingdom","London","Home/Drinkware/","1","9950"
"United States","not available in demo dataset","Home/Shop by Brand/Google/","16","9045"
"Taiwan","Zhongli District","Home/Shop by Brand/YouTube/","1","8415"
"Japan","Osaka","Home/Nest/Nest-USA/","1","8358"
"United States","not available in demo dataset","Home/Electronics/","30","8276"
"Taiwan","(not set)","(not set)","3","7010"
"United States","not available in demo dataset","Home/Bags/More Bags/","1","6930"
"Netherlands","not available in demo dataset","Home/Shop by Brand/Google/","1","6766"
"United States","not available in demo dataset","Home/Apparel/","22","6103"
"United States","Chicago","Home/Electronics/","2","5970"
"United States","Santa Clara","Home/Nest/Nest-USA/","2","5916"
"United States","not available in demo dataset","Home/Shop by Brand/YouTube/","48","5469"
"Japan","Shinjuku","Home/Drinkware/","1","5344"
"United States","Cupertino","Home/Nest/Nest-USA/","1","4998"
"United States","not available in demo dataset","Home/Office/","10","4787"
"United States","Fremont","Home/Nest/Nest-USA/","1","4776"
"Guatemala","not available in demo dataset","Home/Apparel/Headgear/","2","4599"
"United States","Los Angeles","Home/Apparel/","2","4536"
"Brazil","Rio de Janeiro","Home/Apparel/Headgear/","1","4536"
"United States","Sacramento","Home/Apparel/","1","4536"
"Denmark","not available in demo dataset","Home/Drinkware/","2","4200"
"Spain","Barcelona","Home/Drinkware/Water Bottles and Tumblers/","1","3783"
"United States","Mountain View","Home/Electronics/","11","3516"
"United States","New York","Home/Apparel/","3","3240"
"Switzerland","Zurich","Home/Electronics/","1","3184"
"Germany","Munich","Home/Drinkware/","1","3036"
"Thailand","Bangkok","Home/Drinkware/","1","3036"
"Japan","not available in demo dataset","Home/Apparel/","1","3024"
"United States","Mountain View","Home/Drinkware/","3","2945"
"United States","San Francisco","Home/Drinkware/","2","2672"
"United States","San Jose","Home/Nest/Nest-USA/","2","2496"
"United States","Mountain View","Home/Drinkware/Water Bottles and Tumblers/","1","2328"
"Romania","not available in demo dataset","Home/Drinkware/","1","2277"
"United States","Mountain View","Home/Lifestyle/","1","2030"
"India","Pune","Home/Electronics/","1","1990"
"Netherlands","not available in demo dataset","Home/Bags/","3","1859"
"Russia","not available in demo dataset","Home/Apparel/Headgear/","1","1701"
"Indonesia","Jakarta","Home/Shop by Brand/Android/","1","1584"
"Ireland","Dublin","Home/Electronics/","1","1521"
"France","not available in demo dataset","Home/Shop by Brand/YouTube/","2","1501"
"United States","Seattle","Home/Electronics/Power/","1","1475"
"United States","not available in demo dataset","Home/Shop by Brand/Android/","5","1424"
"United States","San Diego","Home/Nest/Nest-USA/","1","1393"
"United Kingdom","not available in demo dataset","Home/Shop by Brand/YouTube/","17","1369"
"United States","Mountain View","Home/Accessories/","8","1354"
"Taiwan","(not set)","Home/Electronics/","1","1344"
"United Kingdom","London","(not set)","1","1309"
"Sweden","not available in demo dataset","Home/Nest/Nest-USA/","1","1232"
"United Kingdom","not available in demo dataset","Home/Nest/Nest-USA/","1","1222"
"United States","not available in demo dataset","Home/Accessories/","18","1199"
"United States","San Jose","Home/Accessories/Stickers/","1","1194"
"United States","San Francisco","Home/Electronics/","2","1176"
"Indonesia","not available in demo dataset","Home/Office/Notebooks & Journals/","1","1160"
"India","not available in demo dataset","Home/Bags/","2","1159"
"United States","Sunnyvale","Home/Electronics/Electronics Accessories/","3","1151"
"United States","Sunnyvale","Home/Spring Sale!/","1","1104"
"United Kingdom","not available in demo dataset","Home/Bags/Backpacks/","1","1089"
"Brazil","not available in demo dataset","Home/Bags/Backpacks/","1","1089"
"United States","Los Angeles","Home/Bags/","3","1053"
"United States","Mountain View","Home/Shop by Brand/Android/","5","1051"
"United States","Kirkland","Home/Electronics/Electronics Accessories/","1","1044"
"France","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","4","1027"
"United States","Chicago","Home/Shop by Brand/YouTube/","3","1026"
"United States","Cambridge","Home/Apparel/Men's/Men's-T-Shirts/","3","1021"
"Canada","Toronto","Home/Drinkware/","1","1002"
"United States","Chicago","Home/Drinkware/Water Bottles and Tumblers/","1","1002"
"France","not available in demo dataset","Home/Bags/","2","975"
"Ireland","Dublin","Home/Accessories/","1","960"
"Canada","not available in demo dataset","Home/Drinkware/Water Bottles and Tumblers/","1","960"
"India","Chennai","Home/Shop by Brand/YouTube/","5","953"
"Italy","not available in demo dataset","Home/Shop by Brand/YouTube/","4","945"
"Hong Kong","(not set)","Home/Bags/","1","910"
"(not set)","(not set)","Home/Bags/","1","910"
"Singapore","(not set)","Home/Bags/More Bags/","1","910"
"United States","Mountain View","Home/Bags/More Bags/","4","872"
"Italy","Rome","Home/Office/","1","848"
"United States","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","30","808"
"United States","Mountain View","Home/Bags/Shopping and Totes/","2","806"
"India","Hyderabad","Home/Shop by Brand/YouTube/","2","805"
"United States","Cambridge","Home/Apparel/Men's/Men's-Outerwear/","3","765"
"Australia","not available in demo dataset","Home/Bags/Backpacks/","2","728"
"New Zealand","not available in demo dataset","Home/Shop by Brand/YouTube/","3","714"
"Germany","not available in demo dataset","Home/Shop by Brand/YouTube/","6","711"
"United States","not available in demo dataset","Home/Lifestyle/","1","711"
"United States","Sunnyvale","Home/Bags/","3","702"
"Taiwan","not available in demo dataset","Home/Apparel/","1","693"
"United States","Mountain View","Home/Apparel/Kid's/","1","693"
"Canada","not available in demo dataset","Home/Electronics/","3","688"
"Mexico","not available in demo dataset","Home/Shop by Brand/YouTube/","3","680"
"Laos","not available in demo dataset","Home/Shop by Brand/YouTube/","2","680"
"Germany","Hamburg","Home/Drinkware/","2","674"
"United States","New York","Home/Office/Writing Instruments/","1","672"
"United States","Seattle","Home/Lifestyle/","1","654"
"United States","Mountain View","Home/Accessories/Fun/","4","650"
"Netherlands","not available in demo dataset","Home/Shop by Brand/YouTube/","3","625"
"Philippines","not available in demo dataset","Home/Electronics/Flashlights/","1","624"
"United Kingdom","not available in demo dataset","Home/Shop by Brand/","1","624"
"Philippines","not available in demo dataset","Home/Bags/","2","598"
"Canada","not available in demo dataset","Home/Apparel/Men's/Men's-Performance Wear/","1","597"
"Canada","Vancouver","Home/Shop by Brand/YouTube/","1","595"
"Japan","not available in demo dataset","Home/Shop by Brand/YouTube/","1","595"
"Hong Kong","Hong Kong","Home/Electronics/Electronics Accessories/","1","595"
"United States","New York","Home/Electronics/","6","594"
"United States","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","15","592"
"Canada","Toronto","Home/Accessories/Fun/","1","584"
"Germany","Berlin","Home/Office/","1","578"
"United States","Pittsburgh","Home/Bags/","1","559"
"Brazil","not available in demo dataset","Home/Accessories/Fun/","2","549"
"Malaysia","not available in demo dataset","Home/Shop by Brand/","1","544"
"United States","Austin","Home/Office/","1","544"
"Canada","not available in demo dataset","Home/Office/Writing Instruments/","1","544"
"United States","New York","(not set)","8","520"
"United States","Mountain View","Home/Apparel/Men's/Men's-T-Shirts/","19","520"
"United States","Mountain View","Home/Apparel/Headgear/","4","519"
"United States","Mountain View","Home/Apparel/Men's/Men's-Outerwear/","5","507"
"Japan","not available in demo dataset","Home/Office/Office Other/","1","507"
"India","Chennai","Home/Apparel/","3","504"
"United States","San Francisco","Home/Shop by Brand/Android/","3","499"
"Canada","Toronto","Home/Bags/","1","495"
"United States","Mountain View","Home/Apparel/Women's/Women's-Performance Wear/","2","470"
"United States","not available in demo dataset","Home/Accessories/Stickers/","7","455"
"Italy","not available in demo dataset","Home/Accessories/Fun/","1","438"
"United Kingdom","not available in demo dataset","Home/Accessories/Fun/","1","438"
"United Kingdom","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","4","432"
"United States","Mountain View","Home/Shop by Brand/Google/","6","430"
"Austria","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","1","429"
"Canada","not available in demo dataset","Home/Accessories/","1","429"
"United States","San Francisco","Home/Office/Notebooks & Journals/","1","429"
"India","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","3","425"
"United States","Mountain View","Home/Apparel/Women's/Women's-Outerwear/","8","400"
"United States","Chicago","Home/Apparel/","1","360"
"Argentina","Buenos Aires","Home/Electronics/Flashlights/","1","352"
"India","Hyderabad","Home/Apparel/","1","351"
"Spain","not available in demo dataset","Home/Shop by Brand/YouTube/","1","350"
"Israel","not available in demo dataset","Home/Shop by Brand/YouTube/","1","350"
"South Korea","not available in demo dataset","Home/Shop by Brand/YouTube/","1","350"
"United States","New York","Home/Shop by Brand/YouTube/","2","350"
"United States","not available in demo dataset","Home/Apparel/Men's/","9","343"
"United States","not available in demo dataset","Home/Electronics/Power/","2","342"
"United States","Sunnyvale","Home/Apparel/Women's/Women's-T-Shirts/","2","330"
"United States","East Lansing","Home/Bags/Backpacks/","1","329"
"United States","Washington","Home/Apparel/Men's/Men's-Performance Wear/","1","327"
"United States","Sunnyvale","Home/Apparel/Men's/Men's-Performance Wear/","2","327"
"United States","Santa Clara","Home/Electronics/","1","325"
"Canada","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","7","314"
"United States","Sunnyvale","Home/Office/Notebooks & Journals/","2","308"
"Japan","not available in demo dataset","Home/Office/","2","306"
"United States","not available in demo dataset","Home/Office/Notebooks & Journals/","2","306"
"United States","San Francisco","Home/Accessories/Stickers/","3","304"
"United States","Chicago","Home/Apparel/Men's/Men's-T-Shirts/","5","304"
"United States","not available in demo dataset","Home/Bags/Backpacks/","5","301"
"United Kingdom","London","Home/Bags/","1","297"
"United States","(not set)","Home/Bags/Backpacks/","1","297"
"Italy","not available in demo dataset","Home/Bags/Backpacks/","1","297"
"Taiwan","(not set)","Home/Apparel/Women's/Women's-Outerwear/","1","297"
"Germany","not available in demo dataset","Home/Bags/Backpacks/","1","297"
"United States","not available in demo dataset","Home/Apparel/Headgear/","17","296"
"Australia","Melbourne","Home/Nest/Nest-USA/","1","294"
"Germany","Munich","Home/Apparel/Headgear/","2","288"
"India","Chennai","Home/Office/Notebooks & Journals/","1","280"
"India","not available in demo dataset","Home/Shop by Brand/YouTube/","7","279"
"United States","Detroit","Drinkware","1","276"
"United States","New York","Home/Bags/","2","274"
"United States","San Francisco","Home/Accessories/Fun/","1","272"
"Sri Lanka","Colombo","Home/Apparel/Men's/Men's-T-Shirts/","2","272"
"Australia","not available in demo dataset","Home/Shop by Brand/YouTube/","4","271"
"United States","New York","Home/Shop by Brand/Android/","2","270"
"United States","San Jose","Home/Electronics/","1","264"
"United States","South San Francisco","Home/Bags/Backpacks/","1","264"
"United States","New York","Home/Apparel/Men's/Men's-T-Shirts/","7","259"
"United States","San Jose","Home/Apparel/","3","256"
"United States","Los Angeles","Home/Shop by Brand/Android/","1","255"
"United States","Sunnyvale","(not set)","4","248"
"Taiwan","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","240"
"Panama","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","240"
"Russia","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","240"
"Japan","Minato","Home/Apparel/Men's/Men's-T-Shirts/","2","240"
"France","Courbevoie","Home/Shop by Brand/","1","240"
"Singapore","Singapore","Home/Apparel/Men's/","1","240"
"Brazil","Sao Paulo","Home/Apparel/Men's/Men's-T-Shirts/","1","240"
"United States","Seattle","Home/Bags/","1","237"
"United States","Mountain View","Waze","1","236"
"United States","Sunnyvale","Home/Office/","2","226"
"United States","San Francisco","Home/Electronics/Power/","1","224"
"Poland","Warsaw","Home/Accessories/Stickers/","1","221"
"United States","Santa Clara","Home/Electronics/Flashlights/","1","220"
"United States","Sunnyvale","Home/Apparel/Headgear/","3","216"
"United States","San Jose","Home/Shop by Brand/YouTube/","2","216"
"France","Paris","Home/Shop by Brand/YouTube/","1","210"
"Réunion","(not set)","Home/Shop by Brand/YouTube/","1","210"
"Ukraine","not available in demo dataset","Home/Shop by Brand/YouTube/","1","210"
"United States","New York","Home/Office/Notebooks & Journals/","2","210"
"Germany","Munich","Home/Shop by Brand/YouTube/","1","210"
"Switzerland","not available in demo dataset","Home/Office/","1","208"
"United States","New York","Home/Shop by Brand/","1","208"
"Poland","Warsaw","Home/Office/","1","208"
"France","not available in demo dataset","Home/Accessories/Stickers/","1","208"
"Brazil","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","4","208"
"Belgium","not available in demo dataset","Home/Accessories/","2","207"
"United Kingdom","London","Home/Shop by Brand/YouTube/","6","200"
"United States","Kirkland","Home/Apparel/Women's/Women's-T-Shirts/","1","199"
"United States","not available in demo dataset","Home/Office/Office Other/","2","192"
"Canada","not available in demo dataset","Home/Shop by Brand/","2","192"
"Taiwan","(not set)","Home/Office/Office Other/","1","192"
"Spain","Madrid","Home/Apparel/Headgear/","1","189"
"Malaysia","Ipoh","Home/Accessories/Housewares/","1","187"
"United States","not available in demo dataset","Home/Bags/Shopping and Totes/","1","186"
"United States","not available in demo dataset","Home/Apparel/Women's/Women's-T-Shirts/","5","183"
"United States","Mountain View","Home/Accessories/Stickers/","3","182"
"United States","San Jose","Home/Apparel/Men's/Men's-T-Shirts/","5","181"
"United States","Sunnyvale","Housewares","1","180"
"Argentina","Santa Fe","Home/Accessories/","1","180"
"Czechia","not available in demo dataset","Home/Shop by Brand/YouTube/","3","179"
"United Kingdom","not available in demo dataset","Home/Accessories/","2","177"
"United States","Washington","Home/Electronics/","1","176"
"United States","Mountain View","Home/Electronics/Flashlights/","1","176"
"United States","Sunnyvale","Home/Bags/Backpacks/","1","170"
"United Kingdom","London","Home/Shop by Brand/Google/","1","170"
"Malaysia","Kuala Lumpur","Home/Bags/","1","169"
"United States","Santa Clara","Home/Apparel/","1","168"
"India","Jaipur","Home/Apparel/","1","168"
"Japan","Minato","Home/Apparel/Headgear/","1","168"
"Japan","Mountain View","Home/Apparel/Headgear/","1","168"
"Hong Kong","Hong Kong","Home/Apparel/","1","168"
"United States","San Jose","Home/Apparel/Headgear/","2","168"
"Germany","not available in demo dataset","Home/Apparel/","1","168"
"United States","New York","Home/Electronics/Electronics Accessories/","2","165"
"Colombia","Bogota","Home/Bags/Backpacks/","1","165"
"Australia","Melbourne","Home/Shop by Brand/YouTube/","3","162"
"United States","San Francisco","Home/Office/","2","158"
"United States","San Francisco","Home/Apparel/","2","157"
"Canada","Calgary","Home/Electronics/Electronics Accessories/","1","156"
"United States","New York","Home/Accessories/Fun/","2","150"
"United States","Seattle","Home/Accessories/","1","144"
"United States","Mountain View","Home/Bags/","1","143"
"United Kingdom","not available in demo dataset","Home/Drinkware/","1","132"
"Germany","not available in demo dataset","Home/Drinkware/","1","132"
"United States","Mountain View","Home/Bags/Backpacks/","3","130"
"South Korea","not available in demo dataset","Home/Accessories/","1","126"
"Taiwan","(not set)","Home/Shop by Brand/YouTube/","1","126"
"United States","Sunnyvale","Home/Apparel/Kid's/Kids-Youth/","1","126"
"United States","not available in demo dataset","Home/Accessories/Fun/","3","123"
"United States","Houston","Home/Shop by Brand/YouTube/","4","123"
"Japan","Yokohama","Home/Shop by Brand/Google/","1","121"
"India","Mumbai","Home/Drinkware/Mugs and Cups/","1","120"
"United States","Mountain View","Home/Electronics/Power/","1","118"
"United States","Pittsburgh","Home/Accessories/","1","117"
"United States","Mountain View","Home/Apparel/Men's/","5","112"
"United States","Mountain View","Home/Apparel/Kid's/Kid's-Toddler/","1","112"
"France","Paris","Home/Apparel/","1","112"
"United States","San Francisco","Home/Apparel/Men's/Men's-T-Shirts/","3","103"
"United States","New York","Lifestyle/","1","102"
"Germany","not available in demo dataset","Home/Accessories/","1","102"
"France","Singapore","Home/Apparel/Men's/Men's-T-Shirts/","1","99"
"Germany","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","3","97"
"United Kingdom","London","Home/Apparel/Men's/Men's-T-Shirts/","2","96"
"Taiwan","(not set)","Home/Apparel/Women's/Women's-T-Shirts/","1","96"
"Germany","Berlin","Home/Accessories/Stickers/","1","96"
"Canada","not available in demo dataset","Home/Shop by Brand/YouTube/","7","95"
"United States","Chicago","Home/Apparel/Women's/Women's-Outerwear/","2","95"
"United States","Cambridge","Home/Shop by Brand/Android/","1","94"
"Pakistan","not available in demo dataset","Home/Shop by Brand/YouTube/","5","94"
"United States","Chicago","Home/Bags/","3","94"
"United States","Salem","Home/Apparel/Men's/Men's-Outerwear/","1","93"
"Netherlands","not available in demo dataset","Home/Electronics/Audio/","1","88"
"United States","Sunnyvale","Home/Shop by Brand/Google/","3","87"
"Colombia","Bogota","Home/Shop by Brand/YouTube/","1","85"
"Ireland","Dublin","Home/Shop by Brand/YouTube/","1","85"
"United States","Mountain View","Home/Apparel/Women's/Women's-T-Shirts/","4","80"
"United States","Los Angeles","Home/Apparel/Kid's/Kids-Youth/","1","80"
"United States","Atlanta","Home/Shop by Brand/","1","80"
"Indonesia","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","2","80"
"United States","San Jose","Home/Apparel/Men's/","2","80"
"Czechia","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","2","80"
"United States","Mountain View","Home/Drinkware/Mugs and Cups/","1","80"
"United States","Los Angeles","Home/Apparel/Men's/","1","80"
"Singapore","Singapore","Home/Accessories/","1","78"
"China","not available in demo dataset","Home/Shop by Brand/Android/","1","78"
"Belarus","not available in demo dataset","Home/Shop by Brand/Google/","1","78"
"Sweden","not available in demo dataset","Home/Shop by Brand/YouTube/","1","78"
"United States","not available in demo dataset","Home/Apparel/Kid's/","1","77"
"Switzerland","Zurich","Home/Bags/","1","77"
"United States","Los Angeles","Home/Apparel/Kid's/","1","77"
"United States","Washington","Home/Apparel/Kid's/Kid's-Infant/","1","77"
"United States","Mountain View","Home/Apparel/Kid's/Kids-Youth/","1","75"
"Serbia","not available in demo dataset","Home/Shop by Brand/YouTube/","3","74"
"United States","Chicago","Home/Shop by Brand/","1","72"
"United States","Mountain View","Home/Apparel/Women's/","1","72"
"China","not available in demo dataset","Home/Apparel/Men's/","1","72"
"United States","New York","Home/Apparel/Headgear/","3","72"
"Turkey","not available in demo dataset","Home/Nest/Nest-USA/","1","70"
"Colombia","Bogota","Home/Shop by Brand/Google/","2","70"
"United States","not available in demo dataset","Home/Drinkware/Mugs and Cups/","1","70"
"Hong Kong","Hong Kong","Home/Bags/More Bags/","1","70"
"Japan","Osaka","Home/Apparel/Kid's/Kid's-Infant/","1","66"
"Finland","Helsinki","(not set)","1","66"
"United States","Austin","Home/Drinkware/Mugs and Cups/","1","65"
"United States","San Francisco","Home/Accessories/","1","65"
"Japan","not available in demo dataset","Home/Electronics/","1","64"
"United States","not available in demo dataset","Wearables/Men's T-Shirts/","1","64"
"Poland","not available in demo dataset","Home/Electronics/","1","64"
"Taiwan","not available in demo dataset","Home/Electronics/","1","64"
"United States","Philadelphia","Home/Apparel/Women's/Women's-T-Shirts/","1","64"
"Tanzania","not available in demo dataset","Home/Shop by Brand/YouTube/","1","63"
"United States","not available in demo dataset","Home/Apparel/Kid's/Kid's-Infant/","1","63"
"Australia","Brisbane","Home/Shop by Brand/YouTube/","1","63"
"United States","Redmond","Home/Shop by Brand/YouTube/","1","63"
"Spain","Madrid","Home/Accessories/","1","60"
"South Korea","Seoul","(not set)","1","60"
"India","Hyderabad","Home/Accessories/","1","57"
"Sweden","Stockholm","Home/Accessories/Pet/","1","56"
"Japan","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","6","56"
"Argentina","not available in demo dataset","Home/Office/","1","54"
"United States","Washington","Home/Office/","1","54"
"United States","Sunnyvale","Home/Bags/Shopping and Totes/","1","54"
"United States","San Bruno","Home/Shop by Brand/YouTube/","1","50"
"Hungary","not available in demo dataset","Home/Shop by Brand/YouTube/","1","50"
"Nepal","not available in demo dataset","Home/Shop by Brand/YouTube/","1","50"
"Israel","Tel Aviv-Yafo","Home/Drinkware/","1","50"
"United States","Mountain View","(not set)","10","50"
"Colombia","not available in demo dataset","Home/Shop by Brand/YouTube/","1","50"
"India","not available in demo dataset","Home/Apparel/Men's/","2","48"
"Singapore","Singapore","Home/Bags/Backpacks/","1","48"
"Pakistan","not available in demo dataset","Home/Drinkware/Water Bottles and Tumblers/","1","48"
"United States","not available in demo dataset","Home/Apparel/Women's/","2","48"
"Taiwan","(not set)","Home/Accessories/Fun/","1","48"
"United States","not available in demo dataset","Home/Accessories/Sports & Fitness/","1","48"
"Singapore","(not set)","Home/Apparel/Men's/Men's-T-Shirts/","2","48"
"Japan","Shinjuku","Home/Accessories/Fun/","1","48"
"United States","San Francisco","Home/Electronics/Electronics Accessories/","1","48"
"United States","Los Angeles","Home/Apparel/Men's/Men's-T-Shirts/","4","48"
"Germany","not available in demo dataset","Home/Apparel/Men's/","1","48"
"United States","Pittsburgh","Home/Apparel/Men's/Men's-T-Shirts/","1","48"
"United States","San Francisco","Home/Office/Writing Instruments/","1","48"
"United States","not available in demo dataset","Home/Electronics/Electronics Accessories/","5","46"
"United Kingdom","not available in demo dataset","Home/Office/","1","45"
"United States","Los Angeles","Home/Shop by Brand/YouTube/","2","42"
"United States","Atlanta","Home/Bags/","1","39"
"Maldives","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","1","39"
"United States","San Jose","Home/Bags/","1","39"
"Ireland","Dublin","Home/Bags/","1","39"
"Georgia","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","1","39"
"India","not available in demo dataset","Home/Apparel/","2","39"
"Estonia","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","1","39"
"United Kingdom","not available in demo dataset","Home/Apparel/Women's/Women's-Outerwear/","1","39"
"United States","Sunnyvale","Home/Accessories/","2","36"
"Israel","not available in demo dataset","Home/Apparel/Kid's/Kid's-Infant/","1","36"
"Hong Kong","Hong Kong","Home/Accessories/","1","36"
"United States","New York","Home/Apparel/Women's/Women's-Performance Wear/","1","36"
"Portugal","not available in demo dataset","Home/Bags/","1","35"
"United States","Cupertino","Home/Shop by Brand/Android/","1","34"
"Austria","not available in demo dataset","Home/Accessories/Housewares/","1","34"
"Netherlands","not available in demo dataset","Home/Accessories/Fun/","1","34"
"Germany","not available in demo dataset","Home/Shop by Brand/Android/","2","34"
"Switzerland","not available in demo dataset","Home/Shop by Brand/Android/","2","34"
"Japan","not available in demo dataset","Home/Shop by Brand/Android/","1","34"
"United States","Chicago","Home/Accessories/Fun/","1","33"
"United Kingdom","(not set)","Home/Accessories/","1","33"
"United States","Mountain View","Home/Apparel/Kid's/Kid's-Infant/","1","33"
"Philippines","not available in demo dataset","Home/Shop by Brand/Google/","1","33"
"Norway","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","32"
"Mexico","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","32"
"United States","Ann Arbor","Home/Apparel/Women's/Women's-T-Shirts/","1","32"
"Denmark","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","32"
"Thailand","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","32"
"Australia","Sydney","Home/Apparel/Men's/Men's-T-Shirts/","1","32"
"Sweden","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","32"
"United States","Seattle","Home/Apparel/Men's/Men's-T-Shirts/","2","32"
"Switzerland","not available in demo dataset","Home/Shop by Brand/YouTube/","1","32"
"Hong Kong","Hong Kong","Home/Apparel/Men's/Men's-T-Shirts/","1","32"
"South Korea","Seoul","Home/Apparel/Men's/Men's-T-Shirts/","1","32"
"Sweden","not available in demo dataset","Home/Drinkware/","1","32"
"India","(not set)","Home/Shop by Brand/YouTube/","2","31"
"Taiwan","Zhongli District","Home/Apparel/","1","30"
"United States","Atlanta","Home/Shop by Brand/YouTube/","1","30"
"Slovakia","not available in demo dataset","Home/Shop by Brand/YouTube/","2","30"
"Vietnam","not available in demo dataset","Home/Shop by Brand/YouTube/","1","30"
"Romania","not available in demo dataset","Home/Shop by Brand/YouTube/","1","30"
"United States","Los Angeles","Home/Shop by Brand/Google/","1","30"
"United States","not available in demo dataset","Home/Apparel/Women's/Women's-Outerwear/","2","29"
"Canada","Toronto","Home/Office/Notebooks & Journals/","1","28"
"France","not available in demo dataset","Home/Accessories/","1","27"
"United States","Chicago","Home/Accessories/","1","27"
"Brazil","not available in demo dataset","Home/Apparel/","1","24"
"Sweden","Stockholm","Home/Drinkware/Mugs and Cups/","1","24"
"United States","Tempe","Home/Apparel/","1","24"
"Netherlands","not available in demo dataset","Home/Apparel/","1","24"
"United States","San Francisco","Home/Apparel/Kid's/Kid's-Infant/","2","24"
"Canada","not available in demo dataset","Home/Drinkware/","1","24"
"Canada","not available in demo dataset","Home/Apparel/","3","24"
"Mexico","Mexico City","Home/Drinkware/","1","24"
"United States","Palo Alto","Home/Apparel/Women's/","1","24"
"Canada","not available in demo dataset","Home/Drinkware/Mugs and Cups/","1","24"
"India","Mumbai","Home/Apparel/Headgear/","1","24"
"Australia","not available in demo dataset","Home/Apparel/Headgear/","1","24"
"United States","Cambridge","Home/Electronics/Electronics Accessories/","1","24"
"South Korea","Seoul","Home/Apparel/","1","24"
"United States","Cambridge","Home/Apparel/Kid's/Kid's-Infant/","1","22"
"United States","not available in demo dataset","Home/Apparel/Kid's/Kid's-Toddler/","1","22"
"United States","New York","Home/Apparel/Kid's/Kid's-Toddler/","1","22"
"United States","Pittsburgh","Home/Apparel/Women's/Women's-T-Shirts/","1","22"
"United States","not available in demo dataset","Home/Office/Writing Instruments/","1","21"
"Ireland","not available in demo dataset","Home/Apparel/","1","21"
"Spain","Barcelona","Home/Shop by Brand/YouTube/","1","20"
"United States","Sunnyvale","Home/Electronics/","3","20"
"United States","Tempe","Home/Apparel/Men's/Men's-T-Shirts/","1","20"
"Russia","not available in demo dataset","Home/Drinkware/","1","20"
"Russia","not available in demo dataset","Home/Shop by Brand/YouTube/","2","20"
"United States","Austin","Home/Electronics/","1","20"
"United Arab Emirates","not available in demo dataset","Home/Shop by Brand/YouTube/","1","20"
"Chile","not available in demo dataset","Home/Shop by Brand/YouTube/","2","20"
"United States","San Francisco","Home/Bags/","1","20"
"United States","Jacksonville","Home/Electronics/Electronics Accessories/","1","20"
"Turkey","not available in demo dataset","Home/Accessories/Stickers/","1","19"
"United States","Austin","Home/Apparel/Women's/Women's-T-Shirts/","1","18"
"United States","Sunnyvale","Home/Apparel/Men's/Men's-T-Shirts/","4","18"
"Iraq","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","16"
"Australia","Perth","(not set)","1","16"
"United States","San Francisco","Home/Apparel/Women's/Women's-Performance Wear/","1","16"
"United States","Los Angeles","Home/Electronics/","1","16"
"Netherlands","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","3","16"
"Italy","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","3","16"
"United States","Houston","Home/Apparel/Men's/","1","16"
"Singapore","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","16"
"India","not available in demo dataset","Home/Apparel/Headgear/","1","16"
"Canada","Vancouver","Home/Electronics/","1","16"
"Dominican Republic","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","16"
"United States","Ann Arbor","Home/Apparel/Men's/Men's-T-Shirts/","2","16"
"India","Bengaluru","Home/Apparel/Men's/Men's-T-Shirts/","1","16"
"United States","Milpitas","Home/Apparel/Women's/Women's-T-Shirts/","1","16"
"United States","Houston","Home/Accessories/","1","15"
"Vietnam","not available in demo dataset","Home/Accessories/","1","15"
"Russia","not available in demo dataset","Home/Accessories/Fun/","1","15"
"South Africa","not available in demo dataset","Home/Shop by Brand/YouTube/","1","14"
"Bahamas","not available in demo dataset","Home/Shop by Brand/YouTube/","1","14"
"Croatia","not available in demo dataset","Home/Shop by Brand/YouTube/","2","14"
"United States","San Jose","Home/Drinkware/Water Bottles and Tumblers/","1","14"
"Netherlands","Amsterdam","Home/Shop by Brand/YouTube/","1","14"
"Norway","not available in demo dataset","Home/Shop by Brand/YouTube/","1","14"
"Italy","Milan","Home/Shop by Brand/YouTube/","1","14"
"Netherlands","not available in demo dataset","Home/Accessories/Stickers/","1","13"
"United States","San Jose","Home/Shop by Brand/Google/","2","12"
"France","Paris","Home/Electronics/","1","11"
"United States","South San Francisco","Home/Accessories/Stickers/","1","11"
"United States","San Francisco","Home/Shop by Brand/Google/","1","10"
"Singapore","not available in demo dataset","Home/Accessories/","1","9"
"Thailand","Bangkok","Home/Shop by Brand/YouTube/","1","9"
"United States","Cambridge","Home/Bags/","1","9"
"New Zealand","not available in demo dataset","Home/Electronics/","1","9"
"(not set)","(not set)","Home/Shop by Brand/YouTube/","1","9"
"Venezuela","not available in demo dataset","Home/Shop by Brand/YouTube/","1","8"
"Spain","Barcelona","Home/Apparel/Men's/","1","8"
"United States","New York","Home/Apparel/Men's/","2","8"
"Netherlands","not available in demo dataset","Home/Bags/Backpacks/","1","7"
"Ireland","not available in demo dataset","Home/Apparel/Headgear/","1","7"
"United States","Austin","Home/Apparel/Men's/Men's-T-Shirts/","1","7"
"Mauritius","not available in demo dataset","Home/Shop by Brand/YouTube/","1","6"
"United States","Mountain View","Home/Electronics/Electronics Accessories/","1","6"
"Mexico","Mexico City","Home/Shop by Brand/YouTube/","1","6"
"Argentina","not available in demo dataset","Home/Shop by Brand/YouTube/","1","6"
"Turkey","not available in demo dataset","Home/Shop by Brand/YouTube/","1","6"
"Italy","not available in demo dataset","Home/Accessories/Stickers/","1","6"
"South Korea","Seoul","Home/Accessories/Stickers/","1","6"
"Spain","not available in demo dataset","Home/Accessories/","1","5"
"Egypt","not available in demo dataset","Home/Shop by Brand/Android/","1","4"
"United States","Dallas","Home/Electronics/","1","4"
"United States","New York","Home/Shop by Brand/Google/","2","4"
"Argentina","Rosario","Home/Apparel/Men's/","1","4"
"Turkey","Istanbul","(not set)","1","3"
"Japan","Minato","Home/Bags/Backpacks/","1","3"
"United States","Menlo Park","Home/Shop by Brand/Google/","1","3"
"United States","Cambridge","(not set)","1","3"
"Bangladesh","(not set)","Home/Shop by Brand/YouTube/","1","2"
"United States","Orlando","Home/Shop by Brand/YouTube/","1","2"
"Morocco","not available in demo dataset","Home/Shop by Brand/Google/","1","2"
"Egypt","not available in demo dataset","Home/Shop by Brand/YouTube/","1","2"
"India","Kolkata","Home/Apparel/Men's/Men's-T-Shirts/","1","2"
"Côte d’Ivoire","not available in demo dataset","Home/Shop by Brand/YouTube/","1","2"
"India","Bengaluru","Home/Shop by Brand/Google/","1","1"
"Taiwan","not available in demo dataset","(not set)","1","0"
"Brazil","not available in demo dataset","(not set)","1","0"
"United States","Mountain View","Home/Electronics/Audio/","1","0"
"Switzerland","not available in demo dataset","Home/Apparel/","1","0"
"Czechia","Prague","Home/Apparel/Headgear/","1","0"
"India","Mumbai","Home/Apparel/","1","0"
"United States","Irvine","Home/Nest/Nest-USA/","1","0"
"Slovakia","Bratislava","(not set)","1","0"
"United States","Austin","Home/Accessories/Pet/","1","0"
"United States","Mountain View","Home/Accessories/Housewares/","1","0"
"United States","Austin","Home/Drinkware/Water Bottles and Tumblers/","1","0"
"Qatar","not available in demo dataset","Home/Apparel/Headgear/","1","0"
"United States","Mountain View","Home/Clearance Sale/","1","0"
"United States","Mountain View","Home/Office/","1","0"
"South Korea","not available in demo dataset","Home/Electronics/Power/","1","0"
"Turkey","Istanbul","Home/Electronics/Audio/","2","0"
"United States","not available in demo dataset","Home/Shop by Brand/","1","0"
"United States","San Francisco","Home/Apparel/Women's/Women's-Outerwear/","1","0"
"United States","San Francisco","Home/Apparel/Men's/","2","0"
"South Africa","not available in demo dataset","Home/Apparel/","1","0"
"Hong Kong","Hong Kong","Home/Electronics/","1","0"
"Switzerland","not available in demo dataset","(not set)","1","0"
"United States","Washington","Home/Apparel/Women's/","1","0"
"United States","Mountain View","Home/Accessories/Sports & Fitness/","1","0"
"Australia","Sydney","Home/Apparel/Men's/","1","0"
"South Korea","Seoul","Home/Accessories/","1","0"
"Poland","Warsaw","Home/Shop by Brand/YouTube/","1","0"
"United States","Ann Arbor","Home/Clearance Sale/","1","0"
"United Kingdom","London","Home/Apparel/Headgear/","1","0"
"United States","Cambridge","Home/Office/Office Other/","1","0"
"Switzerland","Zurich","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","Palo Alto","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"Peru","(not set)","(not set)","1","0"
"United Kingdom","London","Home/Apparel/Women's/Women's-T-Shirts/","1","0"
"Brazil","Fortaleza","Home/Shop by Brand/Android/","1","0"
"United States","San Bruno","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","Palo Alto","(not set)","1","0"
"Greece","not available in demo dataset","Home/Shop by Brand/YouTube/","1","0"
"United States","Los Angeles","Home/Apparel/Women's/","1","0"
"Ireland","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","San Francisco","Home/Shop by Brand/","1","0"
"Canada","not available in demo dataset","Home/Apparel/Headgear/","1","0"
"France","Paris","Home/Bags/","1","0"
"India","Bengaluru","Home/Apparel/Men's/","1","0"
"United States","not available in demo dataset","Home/Accessories/Housewares/","1","0"
"India","Chennai","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","Seattle","Home/Apparel/Headgear/","1","0"
"Canada","Edmonton","Home/Accessories/Pet/","1","0"
"United States","New York","Home/Bags/More Bags/","1","0"
"Canada","Montreal","Home/Apparel/Women's/","1","0"
"Thailand","Bangkok","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"Russia","not available in demo dataset","Home/Electronics/","1","0"
"New Zealand","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"India","not available in demo dataset","Home/Nest/Nest-USA/","1","0"
"United States","San Bruno","(not set)","1","0"
"Canada","Toronto","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","New York","Home/Accessories/Pet/","1","0"
"Greece","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","not available in demo dataset","Home/Gift Cards/","1","0"
"Poland","not available in demo dataset","Home/Office/","1","0"
"Poland","not available in demo dataset","Home/Apparel/Headgear/","1","0"
"United States","San Francisco","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"United Kingdom","not available in demo dataset","Home/Accessories/Stickers/","1","0"
"United States","New York","Home/Bags/Backpacks/","1","0"
"United States","Austin","Home/Apparel/Women's/Women's-Outerwear/","1","0"
"Mexico","Mexico City","Home/Electronics/","1","0"
"Austria","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","Los Angeles","Home/Apparel/Men's/Men's-Performance Wear/","1","0"
"India","not available in demo dataset","Home/Apparel/Women's/Women's-T-Shirts/","1","0"
"United States","Mountain View","Home/Accessories/Pet/","1","0"
"Netherlands","not available in demo dataset","Home/Apparel/Women's/","1","0"
"United States","Santa Clara","Home/Office/","1","0"
"United States","Irvine","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"Spain","Madrid","(not set)","1","0"
"Taiwan","(not set)","Home/Drinkware/","1","0"
"Canada","not available in demo dataset","(not set)","1","0"
"Japan","Shibuya","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"Denmark","not available in demo dataset","Home/Shop by Brand/","1","0"
"Peru","La Victoria","Home/Apparel/","1","0"
"United States","Oakland","Home/Accessories/","1","0"
"Colombia","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"Russia","not available in demo dataset","(not set)","1","0"
"New Zealand","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"Turkey","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"United States","Santa Clara","Home/Bags/","1","0"
"Japan","Minato","Home/Apparel/Men's/Men's-Performance Wear/","1","0"
"United States","San Bruno","Home/Apparel/","1","0"
"United States","Mountain View","${escCatTitle}","1","0"
"United States","San Jose","Home/Electronics/Electronics Accessories/","1","0"
"United States","Mountain View","Home/Apparel/Men's/Men's-Performance Wear/","1","0"
"United States","Chicago","(not set)","1","0"
"United States","Santa Clara","Home/Shop by Brand/Android/","1","0"
"Belgium","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"Philippines","not available in demo dataset","(not set)","1","0"
"United States","Sunnyvale","Home/Electronics/Audio/","1","0"
"Taiwan","Zhongli District","(not set)","1","0"
"France","not available in demo dataset","Home/Apparel/","1","0"
"Spain","not available in demo dataset","Home/Office/Notebooks & Journals/","1","0"
"United States","Seattle","Home/Shop by Brand/YouTube/","1","0"
"India","Pune","(not set)","1","0"
"Mexico","Mexico City","Home/Shop by Brand/Android/","1","0"
"Tunisia","not available in demo dataset","Home/Electronics/Electronics Accessories/","1","0"
"Sweden","not available in demo dataset","Home/Bags/","1","0"
"United Arab Emirates","not available in demo dataset","Home/Apparel/Men's/","1","0"
"United Kingdom","not available in demo dataset","Home/Apparel/Kid's/Kids-Youth/","1","0"
"United States","Sunnyvale","Home/Apparel/Women's/Women's-Outerwear/","1","0"
"United Kingdom","London","Home/Office/","1","0"
"Taiwan","(not set)","Home/Accessories/Housewares/","1","0"
"United Kingdom","not available in demo dataset","Home/Office/Notebooks & Journals/","1","0"
"India","Mumbai","Home/Accessories/Stickers/","1","0"
"Canada","Toronto","Home/Apparel/Men's/","1","0"
"United States","Chicago","Home/Shop by Brand/Android/","1","0"
"Brazil","Sao Paulo","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"Australia","Melbourne","Home/Electronics/","1","0"
"Sweden","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"Canada","Kitchener","Home/Apparel/Headgear/","1","0"
"United States","Austin","Home/Nest/Nest-USA/","1","0"
"Australia","Sydney","(not set)","1","0"
"Indonesia","Jakarta","(not set)","1","0"
"Israel","Tel Aviv-Yafo","(not set)","1","0"
"United States","Kirkland","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"India","Bengaluru","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"United States","San Francisco","Home/Drinkware/Water Bottles and Tumblers/","1","0"
"Philippines","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","Milpitas","Home/Apparel/Women's/Women's-Outerwear/","1","0"
"Japan","not available in demo dataset","Home/Apparel/Men's/","1","0"
"Ireland","not available in demo dataset","Home/Shop by Brand/YouTube/","1","0"
"United States","Paris","Home/Apparel/Women's/Women's-Outerwear/","1","0"
"Switzerland","Zurich","Home/Accessories/Stickers/","1","0"
"Spain","Madrid","Home/Apparel/","1","0"
"United States","Los Angeles","(not set)","2","0"
"United States","not available in demo dataset","Home/Apparel/Men's/Men's-Performance Wear/","3","0"
"Ireland","Dublin","Home/Apparel/","1","0"
"India","Lucknow","Home/Shop by Brand/YouTube/","1","0"
"Poland","not available in demo dataset","Home/Apparel/Women's/Women's-Performance Wear/","1","0"
"India","Hyderabad","Home/Bags/","1","0"
"United States","New York","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"United States","Charlotte","Home/Bags/","1","0"
"United States","Philadelphia","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","San Bruno","Home/Electronics/Audio/","1","0"
"United States","San Jose","(not set)","3","0"
"United Kingdom","not available in demo dataset","Home/Apparel/Men's/","1","0"
"United States","Ann Arbor","Home/Electronics/","1","0"
"Denmark","not available in demo dataset","Home/Apparel/Men's/","2","0"
"Taiwan","(not set)","Home/Accessories/","1","0"
"United States","San Antonio","Home/Drinkware/","1","0"
"Japan","Minato","Home/Office/","1","0"
"Turkey","not available in demo dataset","Home/Electronics/","1","0"
"Argentina","not available in demo dataset","Home/Bags/","1","0"
"Lithuania","not available in demo dataset","(not set)","1","0"
"United States","not available in demo dataset","Home/Clearance Sale/","2","0"
"United States","San Jose","Home/Accessories/Housewares/","2","0"
"Taiwan","(not set)","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","San Francisco","${escCatTitle}","1","0"
"Indonesia","Jakarta","Home/Clearance Sale/","1","0"
"United States","San Jose","Home/Shop by Brand/Android/","1","0"
"Latvia","not available in demo dataset","Home/Bags/More Bags/","1","0"
"United States","Oakland","Home/Apparel/Women's/Women's-Outerwear/","1","0"
"Sri Lanka","not available in demo dataset","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"United States","Los Angeles","Home/Apparel/Women's/Women's-Outerwear/","1","0"
"Canada","not available in demo dataset","Home/Apparel/Men's/","1","0"
"United States","San Jose","Home/Accessories/","1","0"
"Taiwan","not available in demo dataset","Home/Office/","1","0"
"India","not available in demo dataset","Home/Accessories/Pet/","1","0"
"India","Hyderabad","Home/Apparel/Men's/Men's-T-Shirts/","1","0"
"Poland","not available in demo dataset","Home/Bags/More Bags/","1","0"
"United States","Seattle","(not set)","2","0"
"Mexico","not available in demo dataset","Home/Apparel/Men's/Men's-Outerwear/","1","0"
"United States","Sunnyvale","Home/Apparel/","3","0"





**Question 4: What is the top-selling product from each city/country? Can we find any pattern worthy of noting in the products sold?**


SQL Queries:

SELECT a.city, s.productsku, s.name,
    SUM(s.totalordered) AS total_sales
    FROM
        sales_report s
    JOIN
        all_sessions a ON s.productsku = a.productsku
    GROUP BY
        a.city, s.productsku, s.name

country","total_units_sold","total_revenue"
"Bangladesh","2","2"
"Indonesia","311","2824"
"Venezuela","8","8"
"Sweden","134","1454"
"Dominican Republic","1","16"
"Ireland","189","2633"
"Singapore","102","1349"
"Sri Lanka","17","272"
"Laos","170","680"
"Finland","6","66"
"Portugal","5","35"
"Colombia","173","370"
"Ukraine","30","210"
"Latvia","0","0"
"France","261","4410"
"Réunion","30","210"
"Slovakia","30","30"
"Maldives","1","39"
"Israel","103","436"
"Malaysia","58","900"
"Hong Kong","166","1811"
"Philippines","73","1255"
"United States","17293","827646"
"Turkey","38","98"
"(not set)","79","919"
"China","5","150"
"Belarus","2","78"
"Qatar","0","0"
"Netherlands","355","9446"
"Australia","259","1590"
"Mauritius","6","6"
"Serbia","20","74"
"Côte d’Ivoire","2","2"
"Spain","245","4415"
"United Arab Emirates","20","20"
"Georgia","1","39"
"Belgium","18","207"
"Taiwan","397","18555"
"Thailand","264","3077"
"Italy","346","2564"
"United Kingdom","1116","17622"
"Germany","614","6471"
"Canada","895","6767"
"South Korea","98","598"
"Argentina","89","596"
"Egypt","4","6"
"Greece","0","0"
"Bahamas","2","14"
"India","624","7268"
"Chile","8","20"
"Estonia","1","39"
"Vietnam","35","45"
"South Africa","2","14"
"Peru","0","0"
"Japan","868","19102"
"Denmark","352","4232"
"Iraq","1","16"
"Switzerland","44","3535"
"New Zealand","103","723"
"Hungary","50","50"
"Russia","222","1996"
"Norway","4","46"
"Pakistan","96","142"
"Romania","283","2307"
"Brazil","244","6646"
"Austria","13","463"
"Guatemala","198","4599"
"Panama","15","240"
"Lithuania","0","0"
"Croatia","32","14"
"Tunisia","0","0"
"Morocco","96","18708"
"Mexico","376","39746"
"Nepal","50","50"
"Tanzania","9","63"
"Poland","61","493"
"Czechia","184","259"

Answer: by city

city","total_units_sold","total_revenue"
"South San Francisco","22","275"
"Austin","61","654"
"Singapore","25","465"
"Washington","27","634"
"Montreal","6","0"
"Fremont","24","4776"
"Cupertino","44","5032"
"East Lansing","7","329"
"Kuala Lumpur","13","169"
"not available in demo dataset","14165","344707"
"Colombo","17","272"
"Orlando","2","2"
"Stockholm","16","80"
"Bangkok","262","3045"
"Pune","10","1990"
"Calgary","39","156"
"San Antonio","2","0"
"Courbevoie","15","240"
"Zhongli District","169","8445"
"Vancouver","89","611"
"San Jose","234","4920"
"Cambridge","62","1938"
"Rio de Janeiro","189","4536"
"Salem","3","93"
"Tel Aviv-Yafo","50","50"
"Perth","1","16"
"Jaipur","7","168"
"New York","1252","33716"
"San Francisco","1096","52667"
"Berlin","40","674"
"Dallas","4","4"
"Jacksonville","5","20"
"Warsaw","26","429"
"Barcelona","119","3811"
"Edmonton","0","0"
"Rosario","1","4"
"Shibuya","0","0"
"Pittsburgh","199","23034"
"Jakarta","16","1584"
"Ipoh","11","187"
"London","173","12022"
"Philadelphia","4","64"
"Hyderabad","143","1213"
"San Diego","7","1393"
"Amsterdam","2","14"
"Osaka","44","8424"
"Lucknow","0","0"
"Kolkata","2","2"
"Bogota","123","320"
"Dublin","187","2605"
"Palo Alto","342","36088"
"La Victoria","0","0"
"Buenos Aires","16","352"
"Sydney","2","32"
"Brisbane","9","63"
"Rome","53","848"
"Santa Clara","186","6629"
"Chicago","659","35437"
"Houston","129","154"
"Menlo Park","1","3"
"San Bruno","50","50"
"Seattle","171","25696"
"Helsinki","6","66"
"Sao Paulo","15","240"
"Hong Kong","96","901"
"Melbourne","143","456"
"(not set)","477","12473"
"Kitchener","0","0"
"Milan","2","14"
"Fortaleza","0","0"
"Mumbai","6","144"
"Los Angeles","866","73467"
"Ann Arbor","90","48"
"Istanbul","3","3"
"Redmond","9","63"
"Bratislava","0","0"
"Mexico City","102","18736"
"Paris","48","333"
"Mountain View","2496","188576"
"Detroit","23","276"
"Minato","34","411"
"Bengaluru","2","17"
"Sunnyvale","931","68867"
"Sacramento","189","4536"
"Chennai","187","1737"
"Santa Fe","60","180"
"Kirkland","13","1243"
"Irvine","94","0"
"Nashville","94","11186"
"Hamburg","52","674"
"Prague","0","0"
"Milpitas","1","16"
"Oakland","0","0"
"Shinjuku","350","5392"
"Munich","295","3534"
"Zurich","27","3261"
"Yokohama","11","121"
"Charlotte","0","0"
"Madrid","69","249"
"Toronto","502","2109"
"Atlanta","38","149"
"Seoul","39","122"
"Tempe","6","44"



**Question 5: Can we summarize the impact of revenue generated from each city/country?**

SQL Queries:
SELECT
    a.country,
    a.city,
    COUNT(DISTINCT a.totaltransactionrevenue) AS total_transaction,
    SUM(s.totalordered * a.productprice) AS total_revenue,
    AVG(s.totalordered * a.productprice) AS avg_revenue
FROM
    all_sessions a
JOIN sales_report s  
ON a.productsku = s.productsku
JOIN
    products p ON s.productsku = p.sku
WHERE
    p.orderedquantity > 0 
GROUP BY
    a.country, a.city
ORDER BY
    total_transaction DESC;


Answer:

country","city","total_revenue"
"United States","not available in demo dataset","245438"
"United States","Mountain View","188408"
"United States","Los Angeles","73467"
"United States","Sunnyvale","68867"
"United States","San Francisco","52667"
"United States","Palo Alto","36088"
"United States","Chicago","35437"
"United States","New York","33716"
"United States","Seattle","25696"
"United States","Pittsburgh","23034"
"Mexico","not available in demo dataset","21010"
"Mexico","Mexico City","18736"
"Morocco","not available in demo dataset","18708"
"United Kingdom","London","12022"
"United States","Nashville","11186"
"Netherlands","not available in demo dataset","9432"
"Taiwan","(not set)","9113"
"Taiwan","Zhongli District","8445"
"Japan","Osaka","8424"
"United States","Santa Clara","6629"
"United Kingdom","not available in demo dataset","5567"
"Japan","Shinjuku","5392"
"United States","Cupertino","5032"
"United States","San Jose","4920"
"United States","Fremont","4776"
"Guatemala","not available in demo dataset","4599"
"Japan","not available in demo dataset","4586"
"United States","Sacramento","4536"
"Brazil","Rio de Janeiro","4536"
"Denmark","not available in demo dataset","4232"
"Canada","not available in demo dataset","3891"
"Spain","Barcelona","3811"
"France","not available in demo dataset","3738"
"Germany","Munich","3534"
"Switzerland","Zurich","3261"
"Thailand","Bangkok","3045"
"Ireland","Dublin","2605"
"Romania","not available in demo dataset","2307"
"Canada","Toronto","2109"
"Russia","not available in demo dataset","1996"
"India","Pune","1990"
"India","not available in demo dataset","1966"
"United States","Cambridge","1938"
"Brazil","not available in demo dataset","1870"
"India","Chennai","1737"
"Italy","not available in demo dataset","1702"
"Germany","not available in demo dataset","1589"
"Indonesia","Jakarta","1584"
"United States","San Diego","1393"
"Sweden","not available in demo dataset","1374"
"Philippines","not available in demo dataset","1255"
"United States","Kirkland","1243"
"Indonesia","not available in demo dataset","1240"
"India","Hyderabad","1213"
"Australia","not available in demo dataset","1023"
"Taiwan","not available in demo dataset","997"
"Singapore","(not set)","958"
"(not set)","(not set)","919"
"Hong Kong","(not set)","910"
"Hong Kong","Hong Kong","901"
"Italy","Rome","848"
"New Zealand","not available in demo dataset","723"
"Laos","not available in demo dataset","680"
"Germany","Hamburg","674"
"Germany","Berlin","674"
"United States","Austin","654"
"United States","Washington","634"
"Canada","Vancouver","611"
"Malaysia","not available in demo dataset","544"
"South Korea","not available in demo dataset","476"
"Austria","not available in demo dataset","463"
"Australia","Melbourne","456"
"Poland","Warsaw","429"
"Japan","Minato","411"
"Israel","not available in demo dataset","386"
"Singapore","Singapore","366"
"Spain","not available in demo dataset","355"
"Argentina","Buenos Aires","352"
"France","Paris","333"
"United States","East Lansing","329"
"Colombia","Bogota","320"
"United States","(not set)","297"
"United States","Detroit","276"
"United States","South San Francisco","275"
"Switzerland","not available in demo dataset","274"
"Sri Lanka","Colombo","272"
"Czechia","not available in demo dataset","259"
"Spain","Madrid","249"
"Brazil","Sao Paulo","240"
"France","Courbevoie","240"
"Panama","not available in demo dataset","240"
"Ukraine","not available in demo dataset","210"
"Réunion","(not set)","210"
"Belgium","not available in demo dataset","207"
"Malaysia","Ipoh","187"
"Argentina","Santa Fe","180"
"Malaysia","Kuala Lumpur","169"
"Japan","Mountain View","168"
"India","Jaipur","168"
"Canada","Calgary","156"
"United States","Houston","154"
"China","not available in demo dataset","150"
"United States","Atlanta","149"
"India","Mumbai","144"
"Pakistan","not available in demo dataset","142"
"South Korea","Seoul","122"
"Japan","Yokohama","121"
"France","Singapore","99"
"Turkey","not available in demo dataset","95"
"United States","Salem","93"
"Sweden","Stockholm","80"
"Belarus","not available in demo dataset","78"
"Serbia","not available in demo dataset","74"
"Finland","Helsinki","66"
"United States","Philadelphia","64"
"Poland","not available in demo dataset","64"
"Australia","Brisbane","63"
"Tanzania","not available in demo dataset","63"
"United States","Redmond","63"
"Argentina","not available in demo dataset","60"
"United States","San Bruno","50"
"Hungary","not available in demo dataset","50"
"Israel","Tel Aviv-Yafo","50"
"Colombia","not available in demo dataset","50"
"Nepal","not available in demo dataset","50"
"United States","Ann Arbor","48"
"Norway","not available in demo dataset","46"
"Vietnam","not available in demo dataset","45"
"United States","Tempe","44"
"Maldives","not available in demo dataset","39"
"Georgia","not available in demo dataset","39"
"Estonia","not available in demo dataset","39"
"Portugal","not available in demo dataset","35"
"United Kingdom","(not set)","33"
"Australia","Sydney","32"
"Thailand","not available in demo dataset","32"
"India","(not set)","31"
"Slovakia","not available in demo dataset","30"
"Ireland","not available in demo dataset","28"
"Singapore","not available in demo dataset","25"
"Chile","not available in demo dataset","20"
"United States","Jacksonville","20"
"United Arab Emirates","not available in demo dataset","20"
"India","Bengaluru","17"
"Dominican Republic","not available in demo dataset","16"
"United States","Milpitas","16"
"Australia","Perth","16"
"Iraq","not available in demo dataset","16"
"Bahamas","not available in demo dataset","14"
"South Africa","not available in demo dataset","14"
"Netherlands","Amsterdam","14"
"Italy","Milan","14"
"Croatia","not available in demo dataset","14"
"Venezuela","not available in demo dataset","8"
"Mauritius","not available in demo dataset","6"
"Egypt","not available in demo dataset","6"
"United States","Dallas","4"
"Argentina","Rosario","4"
"United States","Menlo Park","3"
"Turkey","Istanbul","3"
"Bangladesh","(not set)","2"
"Côte d’Ivoire","not available in demo dataset","2"
"United States","Orlando","2"
"India","Kolkata","2"
"United States","San Antonio","0"
"Greece","not available in demo dataset","0"
"Czechia","Prague","0"
"India","Lucknow","0"
"Sri Lanka","not available in demo dataset","0"
"United States","Charlotte","0"
"Brazil","Fortaleza","0"
"Slovakia","Bratislava","0"
"Canada","Edmonton","0"
"United States","Oakland","0"
"Peru","La Victoria","0"
"United States","Paris","0"
"Qatar","not available in demo dataset","0"
"Canada","Montreal","0"
"Japan","Shibuya","0"
"Tunisia","not available in demo dataset","0"
"United States","Irvine","0"
"Peru","(not set)","0"
"Canada","Kitchener","0"
"Lithuania","not available in demo dataset","0"
"Latvia","not available in demo dataset","0"









